# Generated by Django 5.0.1 on 2024-01-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_cesfam_rut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat',
            new_name='usuario',
        ),
    ]
